server:
  port: 8088
  undertow:
    io-threads: 4
    worker-threads: 20
    buffer-size: 1024
    direct-buffers: true

spring:
  application:
    name: sun-flower-dubbo-order
dubbo:
  registry:
    address: zookeeper://192.168.1.186:2181
  protocol:
    name: dubbo
    port: 20891
    serialization: kryo
    accesslog: true
  application:
    name: sun-flower-dubbo-order
  provider:
    #accesslog: /Users/chenbo/logs/sun-flower-collection-dubbo/sun-flower-dubbo-order-qua.log
    accesslog: true
    filter: qualityLog
